// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwmtN_mAxYM3dPdx7P_SHqWsm6DQ8grbM',
    appId: '1:329288538059:web:0b0a94affde8e70646084e',
    messagingSenderId: '329288538059',
    projectId: 'language-learning-app-89478',
    authDomain: 'language-learning-app-89478.firebaseapp.com',
    storageBucket: 'language-learning-app-89478.firebasestorage.app',
    measurementId: 'G-V6FQ6JCKYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPtaB3BNFgJwHAnNeUby1IzW-6tldxQYg',
    appId: '1:329288538059:android:46cdbdf8f04fd66546084e',
    messagingSenderId: '329288538059',
    projectId: 'language-learning-app-89478',
    storageBucket: 'language-learning-app-89478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMLGlbatNIobiSac3l01iJassFxL1HycE',
    appId: '1:329288538059:ios:f80ee57dec2948e446084e',
    messagingSenderId: '329288538059',
    projectId: 'language-learning-app-89478',
    storageBucket: 'language-learning-app-89478.firebasestorage.app',
    iosBundleId: 'com.example.cseduapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMLGlbatNIobiSac3l01iJassFxL1HycE',
    appId: '1:329288538059:ios:f80ee57dec2948e446084e',
    messagingSenderId: '329288538059',
    projectId: 'language-learning-app-89478',
    storageBucket: 'language-learning-app-89478.firebasestorage.app',
    iosBundleId: 'com.example.cseduapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwmtN_mAxYM3dPdx7P_SHqWsm6DQ8grbM',
    appId: '1:329288538059:web:dffcf82fdd22a4ee46084e',
    messagingSenderId: '329288538059',
    projectId: 'language-learning-app-89478',
    authDomain: 'language-learning-app-89478.firebaseapp.com',
    storageBucket: 'language-learning-app-89478.firebasestorage.app',
    measurementId: 'G-LXLJ86N9PW',
  );

}